2025-01-09 21:04:31,423 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "D:\UrbanUniversityy\1p\module12\tests_12_4.py", line 19, in test_run
    runner_test1 = Runner(['Бегун Василий'], 10)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\UrbanUniversityy\1p\module12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано list
2025-01-09 21:04:31,424 | WARNING | Неверная скорость для Runner 
Traceback (most recent call last):
  File "D:\UrbanUniversityy\1p\module12\tests_12_4.py", line 9, in test_walk
    runner_test = Runner('Bolt', -10)
                  ^^^^^^^^^^^^^^^^^^^
  File "D:\UrbanUniversityy\1p\module12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -10
